from app.enums.base import BaseEnum

class EducationLevelEnum(BaseEnum):
    SEM_INSTRUCAO = "SEM_INSTRUCAO"
    ENSINO_FUNDAMENTAL_INCOMPLETO = "ENSINO_FUNDAMENTAL_INCOMPLETO"
    ENSINO_FUNDAMENTAL_COMPLETO = "ENSINO_FUNDAMENTAL_COMPLETO"
    ENSINO_MEDIO_COMPLETO = "ENSINO_MEDIO_COMPLETO"
    ENSINO_MEDIO_INCOMPLETO = "ENSINO_MEDIO_INCOMPLETO"
    EDUCACAO_SUPERIOR_COMPLETO = "EDUCACAO_SUPERIOR_COMPLETO"
    EDUCACAO_SUPERIOR_INCOMPLETO = "EDUCACAO_SUPERIOR_INCOMPLETO"